language: php

php:
  - 7.2

install:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction --no-suggest

branches:
  only:
    - master

script:
  - composer test